name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest
    outputs:
      commit_id: ${{ steps.shorten_commit.outputs.commit_id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Shorten commit ID
        id: shorten_commit
        shell: bash
        run: |
          SHORT_COMMIT="${GITHUB_SHA::6}"
          echo "commit_id=$SHORT_COMMIT" >> "$GITHUB_OUTPUT"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: emmytech05/python-app:${{ steps.shorten_commit.outputs.commit_id }}

  CD:
    needs: CI
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        shell: bash
        run: |
          python3 -m pip install --upgrade pip
          pip install yq

      - name: Modify values.yaml with commit ID
        shell: bash
        run: |
          echo "Updating charts/python-app/values.yaml with commit ID..."
          yq -Yi ".image.tag = \"${{ needs.CI.outputs.commit_id }}\"" charts/python-app/values.yaml


      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "update values.yaml with commit ${{ needs.CI.outputs.commit_id }}"
          add: "/charts/python-app/values.yaml"

      - name: Install ArgoCD CLI (arm64)
        shell: bash
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-arm64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/

      - name: Login and sync ArgoCD app
        shell: bash
        run: |
          argocd login argocd-server.argocd \
            --insecure \
            --grpc-web \
            --username admin \
            --password ${{ secrets.ARGOCD_PASSWORD }}
          argocd app sync python-app

