name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Shorten commit ID
        shell: bash
        run: |
          echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: emmytech05/python-app:${{ env.COMMIT_ID }}

  CD:
    needs: CI
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

   CD:
    needs: CI
    runs-on: self-hosted
    steps:
      - name: Install ArgoCD CLI (arm64 for self-hosted runner)
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-arm64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/

      - name: Login and Sync App
        run: |
          argocd login argocd-server.argocd \
            --insecure \
            --grpc-web \
            --username admin \
            --password ${{ secrets.ARGOCD_PASSWORD }}
          argocd app sync python-app

